services:
  CDC-Kafka:
    image: apache/kafka:4.0.0
    hostname: kafka-standalone
    container_name: CDC-Kafka
    ports:
      - 8083:8083
      - 9092:9092
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka-standalone:19092
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-standalone:29093
      - KAFKA_LISTENERS=CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs
      # Region hints for Iceberg (sink) running inside Connect in this container
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_EC2_METADATA_DISABLED=true
      - JAVA_TOOL_OPTIONS=-Daws.region=us-east-1 -Daws.ec2MetadataDisabled=true
      # Optional: raise Kafka request size ceiling if you push large records
      - SOCKET_REQUEST_MAX_BYTES=209715200
    user: root
    volumes:
      - ./kafka/config:/opt/kafka/config-cdc
      - ./kafka/plugins:/opt/kafka/plugins
      - ./data/kafka/tmp:/tmp
      - ./data/kafka/out:/out-kafka
    env_file:
      - ./.env
    deploy:
      replicas: 1
    networks:
      - flink-net

  CDC-Postgres:
    hostname: kafka-postgres
    container_name: CDC-Postgres
    image: postgres:16.2
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/scripts/seed:/docker-entrypoint-initdb.d
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 10s
      retries: 10
    deploy:
      replicas: 1
    networks:
      - flink-net

  CDC-Flink-JobManager:
    build:
      context: .
      dockerfile: Dockerfile.flink
    image: postgres-lakehouse-cdc-flink-jobmanager  # Lowercase
    container_name: CDC-Flink-JobManager
    hostname: flink-jobmanager
    ports:
      - 8081:8081
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_EC2_METADATA_DISABLED=true
      - JAVA_TOOL_OPTIONS=-Daws.region=us-east-1 -Daws.ec2MetadataDisabled=true
    entrypoint: /docker-entrypoint.sh
    command: jobmanager
    volumes:
      - ./flink/jobs:/opt/flink/usrlib
      - ./flink/plugins:/flink/plugins
      - ./flink/conf:/opt/flink/conf
    depends_on:
      CDC-Kafka:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 10s
      timeout: 10s
      retries: 10
    deploy:
      replicas: 1
    networks:
      - flink-net

  CDC-Flink-TaskManager:
    build:
      context: .
      dockerfile: Dockerfile.flink
    image: postgres-lakehouse-cdc-flink-taskmanager  # Lowercase
    container_name: CDC-Flink-TaskManager
    scale: 1
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_EC2_METADATA_DISABLED=true
      - JAVA_TOOL_OPTIONS=-Daws.region=us-east-1 -Daws.ec2MetadataDisabled=true
    entrypoint: /docker-entrypoint.sh
    command: taskmanager
    volumes:
      - ./flink/jobs:/opt/flink/usrlib
      - ./flink/plugins:/flink/plugins
      - ./flink/conf:/opt/flink/conf
    depends_on:
      CDC-Flink-JobManager:
        condition: service_healthy
    deploy:
      replicas: 1
    networks:
      - flink-net

networks:
  flink-net:
    driver: bridge